### ISSUE TITLE
stern throws `unexpected error: parsing time` error during parsing the logs from pods

### ISSUE THREAD

**Issue by Dentrax** [stern/stern#137]
**What happened**:

stern immediately throws an `unexpected error: parsing time` error while gathering logs from pods.

```
unexpected error: parsing time "2021-06-20T08:20:30.331385Z {"": extra text: " {""
```

```
unexpected error: parsing time "2021-06-22T11:57:09.291607285+" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "+" as "Z07:00"
```

**What you expected to happen**:

It should parse the time correctly?

**How to reproduce it (as minimally and precisely as possible)**:

Create a sample app that writes tons of JSON logs, try to scale pods to more than 10.

**Anything else we need to know?**:

```
# this works seamlessly
$ kubectl logs foo-pod-id -c container

# this crashes, while trying to concat all outputs, foo has more than 70 pods
$ stern foo
```

**Environment**:
- stern version (use `stern --version`): `1.19.0`
- OS (e.g: `cat /etc/os-release`):
- Install tools (e.g: Homebrew) `Homebrew`
- Others:

Is it because of data race? Any ideas? 🤔

**Comment by superbrothers** [comment]
Does it work well for applications with a typical amount of logs? For example, do you have problems with nginx container?

**Comment by eliadl** [comment]
I got a similar error when using the `--timestamps` flag with `stern 1.19.0` on macOS 10.14.6:
```
unexpected error: parsing time "2021-07-26T21:38:09.10605837Z ": extra text: " "
```
The pod runs a docker image `FROM python:3.7.10` running `uvicorn 0.13.4`.

---

To be more specific, I ran:
```
stern -n mynamespace -l app=myapp --tail=10 -t=true`
```
And got this output:
```
myapp-7fb4f989f5-nnspl myapp 2021-07-27T00:38:09.106053786+03:00 **CENSORED**
myapp-7fb4f989f5-nnspl myapp 2021-07-27T00:38:09.106056019+03:00 **CENSORED**
unexpected error: parsing time "2021-07-26T21:38:09.10605837Z ": extra text: " "
```

**Comment by Nothing4You** [comment]
just installed this, seeing similar issues on macOS 10.15, stern installed via Homebrew.
cluster is debian based k3s.
`stern --version`
```yaml
version: 1.19.0
```
`kubectl version -o yaml`
```yaml
clientVersion:
  buildDate: "2021-06-16T12:52:14Z"
  compiler: gc
  gitCommit: 092fbfbf53427de67cac1e9fa54aaa09a28371d7
  gitTreeState: clean
  gitVersion: v1.21.2
  goVersion: go1.16.5
  major: "1"
  minor: "21"
  platform: darwin/amd64
serverVersion:
  buildDate: "2021-07-22T20:52:14Z"
  compiler: gc
  gitCommit: 1d1f220fbee9cdeb5416b76b707dde8c231121f2
  gitTreeState: clean
  gitVersion: v1.21.3+k3s1
  goVersion: go1.16.6
  major: "1"
  minor: "21"
  platform: linux/amd64
```

10 containers running, `kubectl logs --timestamps` produces lines starting with this:
```
2021-08-03T01:26:29.663619811+02:00
2021-08-03T01:26:29.800157531+02:00
2021-08-03T01:26:29.818621628+02:00
2021-08-03T01:26:29.953994922+02:00
2021-08-03T01:26:30.156970926+02:00
2021-08-03T01:26:30.167162260+02:00
```
`stern --timestamps` fails like this:
```
unexpected error: parsing time "2021-08-03T01:13:43.292877813+" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "+" as "Z07:00"
unexpected error: parsing time "2021-08-03T01:21:46.006458712+" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "+" as "Z07:00"
unexpected error: parsing time "2021-08-03T01:16:26.581885290+" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "+" as "Z07:00"
unexpected error: parsing time "2021-08-03T01:21:40.942630610+" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "+" as "Z07:00"
unexpected error: parsing time "2021-08-03T01:15:41.958481319+" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "+" as "Z07:00"
unexpected error: parsing time "2021-08-03T01:18:36.855832623+" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "+" as "Z07:00"
unexpected error: parsing time "2021-08-03T01:18:09.042252117+" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "+" as "Z07:00"
unexpected error: parsing time "2021-08-03T01:18:48.660070187+" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "+" as "Z07:00"
unexpected error: parsing time "2021-08-03T01:20:08.294117854+" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "+" as "Z07:00"
unexpected error: parsing time "2021-08-03T01:21:44.361681856+" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "+" as "Z07:00"
```
