### ISSUE TITLE
How to collect logs to file when running in container?

### ISSUE THREAD

**Issue by rnetser** [stern/stern#185]
I am trying to collect cluster logs via a container.
I am using `ghcr.io/stern/stern` and trying to write the output to a file on a mounted volume.
However, I get an error that the output file does not exist.
Running stern command on the container works.

```
---
apiVersion: v1
kind: Pod
metadata:
  name: log-aggregator
  labels:
    app: log-aggregator
  namespace:  infra
spec:
  nodeSelector:
    node-role.kubernetes.io/master: ''
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
    - name: test-runner
      image: ghcr.io/stern/stern:latest
      env:
        - name: KUBECONFIG
          value: /data/auth/kubeconfig
      command:
        - "stern"
        - "'.*'"
        - "--all-namespaces"
        - ">/data/results/stern.log"
      volumeMounts:
        - name: ms-qe-cluster-auth
          mountPath: /data/auth/
        - name: ms-qe-tests-results
          mountPath: /data/results/
      imagePullPolicy: Always
  restartPolicy: Never
  securityContext:
    privileged: true
  volumes:
    - name: ms-qe-cluster-auth
      configMap:
        name: ms-qe-cluster-auth
    - name: ms-qe-tests-results
      emptyDir: {}
``` 

```
❯ oc exec  -n ms-infra-qe ms-qe-log-aggregator -c test-runner -- "stern '.*' -n openshift-service-ca > /data/results/1.log"
time="2022-06-07T12:25:07Z" level=error msg="exec failed: unable to start container process: exec: \"stern '.*' -n openshift-service-ca > /data/results/1.log\": stat stern '.*' -n openshift-service-ca > /data/results/1.log: no such file or directory"
command terminated with exit code 255
```

`oc exec  -n ms-infra-qe ms-qe-log-aggregator -c test-runner -- stern '.*' -n openshift-service-ca` - works but if I add the quotes (to allow the redirect - it does not work)

```
oc debug pod/ms-qe-log-aggregator -n ms-infra-qe -c test-runner 
Starting pod/ms-qe-log-aggregator-debug, command was: stern '.*' --all-namespaces >/data/results/stern.log
warning: Container test-runner is unable to start due to an error: container create failed: time="2022-06-07T12:29:44Z" level=error msg="runc create failed: unable to start container process: exec: \"/bin/sh\": stat /bin/sh: no such file or directory"

warning: Container test-runner is unable to start due to an error: container create failed: time="2022-06-07T12:29:45Z" level=error msg="runc create failed: unable to start container process: exec: \"/bin/sh\": stat /bin/sh: no such file or directory"

```

**Comment by superbrothers** [comment]
You cannot use shell redirection directly in Pod `spec.containers.command`. For example, you can use redirection as follows:

```yaml
      command:
        - /bin/sh
        - -c |
          stern '.*' --all-namespaces >/data/results/stern.log
```

However, `ghcr.io/stern/stern:latest` does not contain a shell. If you want to use a shell, create your own container image as follows:

```dockerfile
FROM busybox

COPY --from=ghcr.io/stern/stern:latest /usr/local/bin/stern /usr/local/bin/stern
```

**Comment by superbrothers** [comment]
> Maybe it will be a good idea to add the redirect option as a command-line argument (thus removing the need to wrap the redirect in a shell)?

Since stern is a CLI tool and redirection generally exists as a shell feature, I don't think it is a good idea to put it in stern.

If you do not want to create a container image, you can use busybox as follows:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: log-aggregator
  labels:
    app: log-aggregator
  namespace:  infra
spec:
  nodeSelector:
    node-role.kubernetes.io/master: ''
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
  initContainers:
    - name: busybox
      image: busybox
      command:
      - cp
      - /bin/busybox
      - /tmp/bin
      volumeMounts:
      - name: bin
        mountPath: /tmp/bin
  containers:
    - name: test-runner
      image: ghcr.io/stern/stern:latest
      env:
        - name: KUBECONFIG
          value: /data/auth/kubeconfig
      command:
        - /bin/busybox
        - sh
        - -c
        - "stern '.*' --all-namespaces >/data/results/stern.log"
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: ms-qe-cluster-auth
          mountPath: /data/auth/
        - name: ms-qe-tests-results
          mountPath: /data/results/
        - name: bin
          mountPath: /bin
          readOnly: true
  restartPolicy: Never
  volumes:
    - name: ms-qe-cluster-auth
      configMap:
        name: ms-qe-cluster-auth
    - name: ms-qe-tests-results
      emptyDir: {}
    - name: bin
      emptyDir: {}
```

Please consider using this method.
