### ISSUE TITLE
Correct Stern clusterrole

### ISSUE THREAD

**Issue by superbrothers** [stern/stern#28]
**Note:** this issue was imported from https://github.com/wercker/stern/issues/106, but it was originally created by [Bulat-Gumerov](https://github.com/Bulat-Gumerov)...

Hey guys, I'm on EKS
I need to create clusterrole for developers which will allow tailing logs with stern and running commands inside k8s pods. I've created this clusterrole:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev-namespace
  name: exec-and-get-logs-from-pods
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
```
Developer can run `kubectl logs`, `kubectl get pods` and `kubectl exec` without any problem, but `stern app` fails with error: failed to set up watch: failed to set up watch: unknown (get pods). I don't want to give `cluster-admin` or `admin` role to our developers.
What's the correct clusterrole for stern?
