### ISSUE TITLE
Stern stops tailing logs after a while (possible log file rotation??)

### ISSUE THREAD

**Issue by rouilj** [stern/stern#287]
**What happened**:

I start stern and it start tailing the log file for my pods. I am using:
```
 stern deployment/roundup-demo
```
After some period of time (a few hours), the logs stop being reported.

**What you expected to happen**:

Logs should continue until I stop stern or the pods are stopped.

**How to reproduce it (as minimally and precisely as possible)**:

I'm not sure exactly. I run two pods that emit output with the following config.yaml:
```
kubelet-arg:
  - container-log-max-files=4
  - container-log-max-size=500Ki
```
The deployment etc can be obtained from: https://wiki.roundup-tracker.org/DeployWithK3s#preview

I am trying to determine if `kubectl logs -f deployment/roundup-demo` is stopping at the same point.

**Anything else we need to know?**:

When stern is properly tailing the pod logs, I have tested that stern follows the new and old log files
when deployment rollout is restarted.

**Environment**:
- stern version (use `stern --version`): 1.27.0
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.6 LTS
- Install tools (e.g: Homebrew): apt
- Others:
   - kubernetes instance: k3s
   - hardware:  odroid-C4

**Comment by tksm** [comment]
Hi,

Thank you for reporting the issue.

I have confirmed that both kubectl and stern stop tailing logs when log file rotations occur in Kubernetes v1.28.0.

I believe the issue is caused by kubernetes/kubernetes#115701, which has been addressed in kubernetes/kubernetes#115702. I have verified that the issue has been resolved in [Kubernetes v1.29.0](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.29.md#v1290).

> Fixed the bug where kubelet couldn't output logs after log file rotated when kubectl logs POD_NAME -f is running. 

## Steps to reproduce

1. Create a Kubernetes cluster using kind with the following config.

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.28.0@sha256:b7a4cad12c197af3ba43202d3efe03246b3f0793f162afb40a33c923952d5b31
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        "container-log-max-size": "1Ki"
```

2. Deploy the following pod.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: p
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: p
    image: busybox
    command: ["/bin/sh", "-c", "while true; do date; sleep 0.01; done"]
```

3. Confirm the issue by observing that both kubectl and stern stop tailing logs in about 10 seconds.

```
stern --timestamps pod/p
kubectl logs --timestamps -f p
```

When we create a Kubernetes v1.29.0 cluster with the same config, the issue is no longer reproduced. (A node image for Kubernetes v1.29.0 is not yet released, so we need to build a v1.29.0 image using `kind build`.)
