### ISSUE TITLE
Support a dynamic list of colors 

### ISSUE THREAD

**Issue by orguz-velo** [stern/stern#298]
**What would you like to be added**:
Being able to define the possible colors to use
**Why is this needed**:
Today, one of the colors used is red. Red is normally used to present errors and when this color is chosen for standard logs, it created confusion.

**Comment by tksm** [comment]
Hi,

How about supporting a list of colors in the configuration file (`~/.config/stern/config.yaml`) using [the SGR sequence format](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters), as shown below?

```yaml
# Green, Yellow, Blue, Magenta, Cyan, White
pod-colors: "32,33,34,35,36,37"

# Colors with underline (4)
# If empty, the pod colors will be used as container colors
container-colors: "32;4,33;4,34;4,35;4,36;4,37;4"
```

This format enables the use of various attributes, such as underline, background colors, 8-bit colors, and 24-bit colors, if your terminal supports them.

The screenshot below shows an example of using [24-bit colors](https://en.wikipedia.org/wiki/ANSI_escape_code#24-bit) with the Monokai theme.

![image](https://github.com/stern/stern/assets/9250296/55071f91-1b20-44a9-b68f-91d6034fe274)
