### ISSUE TITLE
kubectl krew install stern - not working

### ISSUE THREAD

**Issue by aloner-pro** [stern/stern#336]
`❯ kubectl krew install stern`
`failed to retrieve plugin indexes: failed to list the remote URL for index default: command execution failure, output="": exit status 1
Error: exit status 1`

This is what I am getting.
Platform - Windows 11
Powershell

**Comment by superbrothers** [comment]
Can you download the archive file from the URL below and execute the stern binary file normally?

```
    - bin: stern.exe
      uri: https://github.com/stern/stern/releases/download/v1.32.0/stern_1.32.0_windows_arm64.tar.gz
      sha256: 5733760fd98225d8df6ef686eed965422ff5dd3ab5a32827d012a1106bf346f6
      selector:
        matchLabels:
          os: windows
          arch: arm64
    - bin: stern.exe
      uri: https://github.com/stern/stern/releases/download/v1.32.0/stern_1.32.0_windows_amd64.tar.gz
      sha256: 809b9e0f987c49948b66a7eade7ad660d3541db09ff21b56f3e2d1901b5d580d
      selector:
        matchLabels:
          os: windows
          arch: amd64
```

https://github.com/kubernetes-sigs/krew-index/blob/e5acd0bb63a521909fe945b820bc65302a9e5338/plugins/stern.yaml
